# embed_lua.cmake — generate a C header that embeds Lua modules as byte arrays.
#
# gramarye_embed_lua(<out_header> <name1> <path1> [<name2> <path2> ...])
#
# Emits, for each module, a `static const char <ident>_src[]` byte array and a
# `g_lua_modules[]` registry table of { name, src, len }. Bytes are written as a
# comma-separated initializer (not a string literal) to dodge compiler string-
# length limits and any embedding/quoting hazards. Runs at configure time; the
# caller should add the source paths to CMAKE_CONFIGURE_DEPENDS so edits
# regenerate the header.
function(gramarye_embed_lua out_header)
    set(modules ${ARGN})
    list(LENGTH modules count)
    math(EXPR last "${count} - 1")

    set(body "// Auto-generated by cmake/embed_lua.cmake — do not edit.\n")
    string(APPEND body "#ifndef GRAMARYE_UI_LUA_MODULES_H\n")
    string(APPEND body "#define GRAMARYE_UI_LUA_MODULES_H\n\n")
    string(APPEND body "typedef struct { const char *name; const char *src; int len; } GramaryeLuaModule;\n\n")

    set(table "static const GramaryeLuaModule g_lua_modules[] = {\n")

    foreach(i RANGE 0 ${last} 2)
        list(GET modules ${i} mod_name)
        math(EXPR j "${i} + 1")
        list(GET modules ${j} mod_path)

        string(MAKE_C_IDENTIFIER "${mod_name}" sym)
        file(READ "${mod_path}" hex HEX)
        string(LENGTH "${hex}" hexlen)
        math(EXPR bytelen "${hexlen} / 2")
        string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")

        string(APPEND body "static const char ${sym}_src[] = { ${bytes} };\n")
        string(APPEND table "    { \"${mod_name}\", ${sym}_src, ${bytelen} },\n")
    endforeach()

    string(APPEND table "};\n")
    string(APPEND body "\n${table}\n#endif // GRAMARYE_UI_LUA_MODULES_H\n")

    file(WRITE "${out_header}" "${body}")
endfunction()
